<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Await-Async</title>
</head>
<body>
<script>
	// const 摇色子 = () => {
	// 	return new Promise((resolve,reject) => {
	// 		setTimeout(() => {
	// 			resolve(Math.floor(Math.random()*6 +1))
	//     },3000)
	//   })
	// }
	// const fn = async ()=> {
	// 	let result = await 摇色子()
	// 	console.log(result);
	// }
	// fn()

	async function 摇色子() {
		throw new Error('色子坏了')
	}

	async function fn() {
		try {
			let result = await 摇色子()
			console.log(result);
		} catch (e) {
			console.log(e);
		}
	}

	fn() //Error: 色子坏了

	const ajax = () => {
		return new Promise((resolve, reject) => {
			// resolve({data: {name: '韩宝亿'}})
			reject({status: 403})
		})
	}
	const fn1 = async () => {
		try {
			const result = await ajax()
			console.log(result);  //data: {name: "韩宝亿"}
		} catch (e) {
			console.log(e); //{status: 403}
		}
	}
	fn1()


  /*可以用await+then(null,onRejected)来优雅的进行错误处理，摒弃try-catch*/
	const ajax1 = () => {
		return new Promise((resolve, reject) => {
			resolve({data: {name: '韩宝亿'}})
			// reject({status: 403})
		})
	}
	const error = e => {
		console.log(e); //{status: 403}
	}
	const fn2 = async () => {
		const result = await ajax1().then(null, error) //result接受成功返回值，error处理错误
		console.log(result);  //data: {name: "韩宝亿"}
	}
	fn2()
</script>
</body>
</html>